export const countryCodeOptions = {
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BA": "Bosnia and Herzegovina",
  "BB": "Barbados",
  "WF": "Wallis and Futuna",
  "BL": "Saint Barthelemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BT": "Bhutan",
  "JM": "Jamaica",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "WS": "Samoa",
  "BQ": "Bonaire",
  "BR": "Brazil",
  "BS": "Bahamas",
  "JE": "Jersey",
  "BY": "Belarus",
  "BZ": "Belize",
  "RU": "Russia",
  "RW": "Rwanda",
  "RS": "Serbia",
  "TL": "East Timor",
  "RE": "Reunion",
  "TM": "Turkmenistan",
  "TJ": "Tajikistan",
  "RO": "Romania",
  "TK": "Tokelau",
  "GW": "Guinea-Bissau",
  "GU": "Guam",
  "GT": "Guatemala",
  "GS": "South Georgia and the South Sandwich Islands",
  "GR": "Greece",
  "GQ": "Equatorial Guinea",
  "GP": "Guadeloupe",
  "JP": "Japan",
  "GY": "Guyana",
  "GG": "Guernsey",
  "GF": "French Guiana",
  "GE": "Georgia",
  "GD": "Grenada",
  "GB": "United Kingdom",
  "GA": "Gabon",
  "SV": "El Salvador",
  "GN": "Guinea",
  "GM": "Gambia",
  "GL": "Greenland",
  "GI": "Gibraltar",
  "GH": "Ghana",
  "OM": "Oman",
  "TN": "Tunisia",
  "JO": "Jordan",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "HK": "Hong Kong",
  "HN": "Honduras",
  "HM": "Heard Island and McDonald Islands",
  "VE": "Venezuela",
  "PR": "Puerto Rico",
  "PS": "Palestinian Territory",
  "PW": "Palau",
  "PT": "Portugal",
  "SJ": "Svalbard and Jan Mayen",
  "PY": "Paraguay",
  "IQ": "Iraq",
  "PA": "Panama",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PE": "Peru",
  "PK": "Pakistan",
  "PH": "Philippines",
  "PN": "Pitcairn",
  "PL": "Poland",
  "PM": "Saint Pierre and Miquelon",
  "ZM": "Zambia",
  "EH": "Western Sahara",
  "EE": "Estonia",
  "EG": "Egypt",
  "ZA": "South Africa",
  "EC": "Ecuador",
  "IT": "Italy",
  "VN": "Vietnam",
  "SB": "Solomon Islands",
  "ET": "Ethiopia",
  "SO": "Somalia",
  "ZW": "Zimbabwe",
  "SA": "Saudi Arabia",
  "ES": "Spain",
  "ER": "Eritrea",
  "ME": "Montenegro",
  "MD": "Moldova",
  "MG": "Madagascar",
  "MF": "Saint Martin",
  "MA": "Morocco",
  "MC": "Monaco",
  "UZ": "Uzbekistan",
  "MM": "Myanmar",
  "ML": "Mali",
  "MO": "Macao",
  "MN": "Mongolia",
  "MH": "Marshall Islands",
  "MK": "Macedonia",
  "MU": "Mauritius",
  "MT": "Malta",
  "MW": "Malawi",
  "MV": "Maldives",
  "MQ": "Martinique",
  "MP": "Northern Mariana Islands",
  "MS": "Montserrat",
  "MR": "Mauritania",
  "IM": "Isle of Man",
  "UG": "Uganda",
  "TZ": "Tanzania",
  "MY": "Malaysia",
  "MX": "Mexico",
  "IL": "Israel",
  "FR": "France",
  "IO": "British Indian Ocean Territory",
  "SH": "Saint Helena",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falkland Islands",
  "FM": "Micronesia",
  "FO": "Faroe Islands",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NA": "Namibia",
  "VU": "Vanuatu",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NZ": "New Zealand",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "CK": "Cook Islands",
  "XK": "Kosovo",
  "CI": "Ivory Coast",
  "CH": "Switzerland",
  "CO": "Colombia",
  "CN": "China",
  "CM": "Cameroon",
  "CL": "Chile",
  "CC": "Cocos Islands",
  "CA": "Canada",
  "CG": "Republic of the Congo",
  "CF": "Central African Republic",
  "CD": "Democratic Republic of the Congo",
  "CZ": "Czech Republic",
  "CY": "Cyprus",
  "CX": "Christmas Island",
  "CR": "Costa Rica",
  "CW": "Curacao",
  "CV": "Cape Verde",
  "CU": "Cuba",
  "SZ": "Swaziland",
  "SY": "Syria",
  "SX": "Sint Maarten",
  "KG": "Kyrgyzstan",
  "KE": "Kenya",
  "SS": "South Sudan",
  "SR": "Suriname",
  "KI": "Kiribati",
  "KH": "Cambodia",
  "KN": "Saint Kitts and Nevis",
  "KM": "Comoros",
  "ST": "Sao Tome and Principe",
  "SK": "Slovakia",
  "KR": "South Korea",
  "SI": "Slovenia",
  "KP": "North Korea",
  "KW": "Kuwait",
  "SN": "Senegal",
  "SM": "San Marino",
  "SL": "Sierra Leone",
  "SC": "Seychelles",
  "KZ": "Kazakhstan",
  "KY": "Cayman Islands",
  "SG": "Singapore",
  "SE": "Sweden",
  "SD": "Sudan",
  "DO": "Dominican Republic",
  "DM": "Dominica",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "VG": "British Virgin Islands",
  "DE": "Germany",
  "YE": "Yemen",
  "DZ": "Algeria",
  "US": "United States",
  "UY": "Uruguay",
  "YT": "Mayotte",
  "UM": "United States Minor Outlying Islands",
  "LB": "Lebanon",
  "LC": "Saint Lucia",
  "LA": "Laos",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TT": "Trinidad and Tobago",
  "TR": "Turkey",
  "LK": "Sri Lanka",
  "LI": "Liechtenstein",
  "LV": "Latvia",
  "TO": "Tonga",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LR": "Liberia",
  "LS": "Lesotho",
  "TH": "Thailand",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TD": "Chad",
  "TC": "Turks and Caicos Islands",
  "LY": "Libya",
  "VA": "Vatican",
  "VC": "Saint Vincent and the Grenadines",
  "AE": "United Arab Emirates",
  "AD": "Andorra",
  "AG": "Antigua and Barbuda",
  "AF": "Afghanistan",
  "AI": "Anguilla",
  "VI": "U.S. Virgin Islands",
  "IS": "Iceland",
  "IR": "Iran",
  "AM": "Armenia",
  "AL": "Albania",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AS": "American Samoa",
  "AR": "Argentina",
  "AU": "Australia",
  "AT": "Austria",
  "AW": "Aruba",
  "IN": "India",
  "AX": "Aland Islands",
  "AZ": "Azerbaijan",
  "IE": "Ireland",
  "ID": "Indonesia",
  "UA": "Ukraine",
  "QA": "Qatar",
  "MZ": "Mozambique"
}

export const countryOptions = [
  {code: 'AF', name: 'Afghanistan'},
	{code: 'AL', name: 'Albania'},
	{code: 'DZ', name: 'Algeria'},
	{code: 'AS', name: 'American Samoa'},
	{code: 'AD', name: 'Andorra'},
	{code: 'AO', name: 'Angola'},
	{code: 'AI', name: 'Anguilla'},
	{code: 'AG', name: 'Antigua and Barbuda'},
	{code: 'AR', name: 'Argentina'},
	{code: 'AM', name: 'Armenia'},
	{code: 'AW', name: 'Aruba'},
	{code: 'AU', name: 'Australia'},
	{code: 'AT', name: 'Austria'},
	{code: 'AZ', name: 'Azerbaijan'},
	{code: 'BS', name: 'Bahamas'},
	{code: 'BH', name: 'Bahrain'},
	{code: 'BD', name: 'Bangladesh'},
	{code: 'BB', name: 'Barbados'},
	{code: 'BY', name: 'Belarus'},
	{code: 'BE', name: 'Belgium'},
	{code: 'BZ', name: 'Belize'},
	{code: 'BJ', name: 'Benin'},
	{code: 'BM', name: 'Bermuda'},
	{code: 'BT', name: 'Bhutan'},
	{code: 'BO', name: 'Bolivia'},
	{code: 'BA', name: 'Bosnia and Herzegovina'},
	{code: 'BW', name: 'Botswana'},
	{code: 'BV', name: 'Bouvet Island'},
	{code: 'BR', name: 'Brazil'},
	{code: 'BN', name: 'Brunei Darussalam'},
	{code: 'BG', name: 'Bulgaria'},
	{code: 'BF', name: 'Burkina Faso'},
	{code: 'BI', name: 'Burundi'},
	{code: 'KH', name: 'Cambodia'},
	{code: 'CM', name: 'Cameroon'},
	{code: 'CA', name: 'Canada'},
	{code: 'CV', name: 'Cape Verde'},
	{code: 'KY', name: 'Cayman Islands'},
	{code: 'CF', name: 'Central African Republic'},
	{code: 'TD', name: 'Chad'},
	{code: 'CL', name: 'Chile'},
	{code: 'CN', name: 'China'},
	{code: 'CO', name: 'Colombia'},
	{code: 'KM', name: 'Comoros'},
	{code: 'CG', name: 'Congo'},
	{code: 'CD', name: 'Congo, The Democratic Republic of the'},
	{code: 'CK', name: 'Cook Islands'},
	{code: 'CR', name: 'Costa Rica'},
	{code: 'CI', name: "Cote D'Ivoire"},
	{code: 'HR', name: 'Croatia'},
	{code: 'CU', name: 'Cuba'},
	{code: 'CY', name: 'Cyprus'},
	{code: 'CZ', name: 'Czech Republic'},
	{code: 'DK', name: 'Denmark'},
	{code: 'DJ', name: 'Djibouti'},
	{code: 'DM', name: 'Dominica'},
	{code: 'DO', name: 'Dominican Republic'},
	{code: 'EC', name: 'Ecuador'},
	{code: 'EG', name: 'Egypt'},
	{code: 'SV', name: 'El Salvador'},
	{code: 'GQ', name: 'Equatorial Guinea'},
	{code: 'ER', name: 'Eritrea'},
	{code: 'EE', name: 'Estonia'},
	{code: 'ET', name: 'Ethiopia'},
	{code: 'FK', name: 'Falkland Islands (Malvinas)'},
	{code: 'FO', name: 'Faroe Islands'},
	{code: 'FJ', name: 'Fiji'},
	{code: 'FI', name: 'Finland'},
	{code: 'FR', name: 'France'},
	{code: 'GF', name: 'French Guiana'},
	{code: 'PF', name: 'French Polynesia'},
	{code: 'GA', name: 'Gabon'},
	{code: 'GM', name: 'Gambia'},
	{code: 'GE', name: 'Georgia'},
	{code: 'DE', name: 'Germany'},
	{code: 'GH', name: 'Ghana'},
	{code: 'GI', name: 'Gibraltar'},
	{code: 'GR', name: 'Greece'},
	{code: 'GL', name: 'Greenland'},
	{code: 'GD', name: 'Grenada'},
	{code: 'GU', name: 'Guam'},
	{code: 'GT', name: 'Guatemala'},
	{code: 'GG', name: 'Guernsey'},
	{code: 'GN', name: 'Guinea'},
	{code: 'GW', name: 'Guinea-Bissau'},
	{code: 'GY', name: 'Guyana'},
	{code: 'HT', name: 'Haiti'},
	{code: 'HM', name: 'Heard Island and Mcdonald Islands'},
	{code: 'VA', name: 'Holy See (Vatican City State)'},
	{code: 'HN', name: 'Honduras'},
	{code: 'HK', name: 'Hong Kong'},
	{code: 'HU', name: 'Hungary'},
	{code: 'IS', name: 'Iceland'},
	{code: 'IN', name: 'India'},
	{code: 'ID', name: 'Indonesia'},
	{code: 'IR', name: 'Iran, Islamic Republic Of'},
	{code: 'IQ', name: 'Iraq'},
	{code: 'IE', name: 'Ireland'},
	{code: 'IM', name: 'Isle of Man'},
	{code: 'IL', name: 'Israel'},
	{code: 'IT', name: 'Italy'},
	{code: 'JM', name: 'Jamaica'},
	{code: 'JP', name: 'Japan'},
	{code: 'JE', name: 'Jersey'},
	{code: 'JO', name: 'Jordan'},
	{code: 'KZ', name: 'Kazakhstan'},
	{code: 'KE', name: 'Kenya'},
	{code: 'KI', name: 'Kiribati'},
	{code: 'KP', name: "Korea, Democratic People's Republic of"},
	{code: 'KR', name: 'Korea, Republic of'},
	{code: 'KW', name: 'Kuwait'},
	{code: 'KG', name: 'Kyrgyzstan'},
	{code: 'LA', name: "Lao People's Democratic Republic"},
	{code: 'LV', name: 'Latvia'},
	{code: 'LB', name: 'Lebanon'},
	{code: 'LS', name: 'Lesotho'},
	{code: 'LR', name: 'Liberia'},
	{code: 'LY', name: 'Libyan Arab Jamahiriya'},
	{code: 'LI', name: 'Liechtenstein'},
	{code: 'LT', name: 'Lithuania'},
	{code: 'LU', name: 'Luxembourg'},
	{code: 'MO', name: 'Macao'},
	{code: 'MK', name: 'Macedonia, The Former Yugoslav Republic of'},
	{code: 'MG', name: 'Madagascar'},
	{code: 'MW', name: 'Malawi'},
	{code: 'MY', name: 'Malaysia'},
	{code: 'MV', name: 'Maldives'},
	{code: 'ML', name: 'Mali'},
	{code: 'MT', name: 'Malta'},
	{code: 'MH', name: 'Marshall Islands'},
	{code: 'MQ', name: 'Martinique'},
	{code: 'MR', name: 'Mauritania'},
	{code: 'MU', name: 'Mauritius'},
	{code: 'YT', name: 'Mayotte'},
	{code: 'MX', name: 'Mexico'},
	{code: 'FM', name: 'Micronesia, Federated States of'},
	{code: 'MD', name: 'Moldova, Republic of'},
	{code: 'MC', name: 'Monaco'},
	{code: 'MN', name: 'Mongolia'},
	{code: 'MS', name: 'Montserrat'},
	{code: 'MA', name: 'Morocco'},
	{code: 'MZ', name: 'Mozambique'},
	{code: 'MM', name: 'Myanmar'},
	{code: 'NA', name: 'Namibia'},
	{code: 'NR', name: 'Nauru'},
	{code: 'NP', name: 'Nepal'},
	{code: 'NL', name: 'Netherlands'},
	{code: 'AN', name: 'Netherlands Antilles'},
	{code: 'NC', name: 'New Caledonia'},
	{code: 'NZ', name: 'New Zealand'},
	{code: 'NI', name: 'Nicaragua'},
	{code: 'NE', name: 'Niger'},
	{code: 'NG', name: 'Nigeria'},
	{code: 'MP', name: 'Northern Mariana Islands'},
	{code: 'NO', name: 'Norway'},
	{code: 'OM', name: 'Oman'},
	{code: 'PK', name: 'Pakistan'},
	{code: 'PW', name: 'Palau'},
	{code: 'PA', name: 'Panama'},
	{code: 'PG', name: 'Papua New Guinea'},
	{code: 'PY', name: 'Paraguay'},
	{code: 'PE', name: 'Peru'},
	{code: 'PH', name: 'Philippines'},
	{code: 'PL', name: 'Poland'},
	{code: 'PT', name: 'Portugal'},
	{code: 'PR', name: 'Puerto Rico'},
	{code: 'QA', name: 'Qatar'},
	{code: 'RE', name: 'Reunion'},
	{code: 'RO', name: 'Romania'},
	{code: 'RU', name: 'Russian Federation'},
	{code: 'RW', name: 'Rwanda'},
	{code: 'SH', name: 'Saint Helena'},
	{code: 'KN', name: 'Saint Kitts and Nevis'},
	{code: 'LC', name: 'Saint Lucia'},
	{code: 'PM', name: 'Saint Pierre and Miquelon'},
	{code: 'VC', name: 'Saint Vincent and the Grenadines'},
	{code: 'WS', name: 'Samoa'},
	{code: 'SM', name: 'San Marino'},
	{code: 'ST', name: 'Sao Tome and Principe'},
	{code: 'SA', name: 'Saudi Arabia'},
	{code: 'SN', name: 'Senegal'},
	{code: 'SC', name: 'Seychelles'},
	{code: 'SL', name: 'Sierra Leone'},
	{code: 'SG', name: 'Singapore'},
	{code: 'SK', name: 'Slovakia'},
	{code: 'SI', name: 'Slovenia'},
	{code: 'SB', name: 'Solomon Islands'},
	{code: 'SO', name: 'Somalia'},
	{code: 'ZA', name: 'South Africa'},
	{code: 'ES', name: 'Spain'},
	{code: 'LK', name: 'Sri Lanka'},
	{code: 'SD', name: 'Sudan'},
	{code: 'SR', name: 'Suriname'},
	{code: 'SZ', name: 'Swaziland'},
	{code: 'SE', name: 'Sweden'},
	{code: 'CH', name: 'Switzerland'},
	{code: 'SY', name: 'Syrian Arab Republic'},
	{code: 'TW', name: 'Taiwan, Province of China'},
	{code: 'TJ', name: 'Tajikistan'},
	{code: 'TZ', name: 'Tanzania, United Republic of'},
	{code: 'TH', name: 'Thailand'},
	{code: 'TL', name: 'Timor-Leste'},
	{code: 'TG', name: 'Togo'},
	{code: 'TO', name: 'Tonga'},
	{code: 'TT', name: 'Trinidad and Tobago'},
	{code: 'TN', name: 'Tunisia'},
	{code: 'TR', name: 'Turkey'},
	{code: 'TM', name: 'Turkmenistan'},
	{code: 'TC', name: 'Turks and Caicos Islands'},
	{code: 'TV', name: 'Tuvalu'},
	{code: 'UG', name: 'Uganda'},
	{code: 'UA', name: 'Ukraine'},
	{code: 'AE', name: 'United Arab Emirates'},
	{code: 'GB', name: 'United Kingdom'},
	{code: 'US', name: 'United States'},
	{code: 'UY', name: 'Uruguay'},
	{code: 'UZ', name: 'Uzbekistan'},
	{code: 'VU', name: 'Vanuatu'},
	{code: 'VE', name: 'Venezuela'},
	{code: 'VN', name: 'Viet Nam'},
	{code: 'VG', name: 'Virgin Islands, British'},
	{code: 'VI', name: 'Virgin Islands, U.S.'},
	{code: 'WF', name: 'Wallis and Futuna'},
	{code: 'YE', name: 'Yemen'},
	{code: 'ZM', name: 'Zambia'},
	{code: 'ZW', name: 'Zimbabwe'}]

export const countryColors = {
  'BD': '#f2510e',
  'BE': '#61da5e',
  'BF': '#34891f',
  'BG': '#da967d',
  'BA': '#b11573',
  'BB': '#651be6',
  'WF': '#e3d94c',
  'BM': '#01ac53',
  'BN': '#2f7b99',
  'BO': '#996635',
  'BH': '#c0a43c',
  'BI': '#b0d87b',
  'BJ': '#9348af',
  'BT': '#c5a4fb',
  'JM': '#d6dd92',
  'BV': '#75d89e',
  'BW': '#4bb473',
  'WS': '#f07815',
  'BR': '#2f3f94',
  'BS': '#d2737d',
  'JE': '#b2be57',
  'BY': '#79806e',
  'BZ': '#cd2f00',
  'RU': '#17232',
  'RW': '#608572',
  'TL': '#c9d730',
  'RE': '#ce00be',
  'TM': '#d3493a',
  'TJ': '#0f525f',
  'RO': '#32d5d6',
  'GW': '#fb21a3',
  'GU': '#b2b4f0',
  'GT': '#c3c89d',
  'GR': '#6749e8',
  'GQ': '#5d2c52',
  'JP': '#e33e52',
  'GY': '#51aed9',
  'GG': '#c9a941',
  'GF': '#088baf',
  'GE': '#05d371',
  'GD': '#8fb413',
  'GB': '#4a543f',
  'GA': '#e145ba',
  'GN': '#41d158',
  'GM': '#ee91e3',
  'GL': '#0971f0',
  'GI': '#802234',
  'GH': '#4834d0',
  'OM': '#7a3d93',
  'TN': '#640fc1',
  'JO': '#fa06ec',
  'HR': '#250662',
  'HT': '#5bb32d',
  'HU': '#7fb411',
  'HK': '#d36647',
  'HN': '#89d534',
  'HM': '#807fb',
  'VE': '#7260d8',
  'PR': '#fff4d7',
  'PW': '#93f2d7',
  'PT': '#10e5b1',
  'KN': '#00f87c',
  'PY': '#0f5997',
  'IQ': '#983f7a',
  'PA': '#9b5c2a',
  'PF': '#f158bf',
  'PG': '#15b9ee',
  'PE': '#409188',
  'PK': '#635f6d',
  'PH': '#911e20',
  'PL': '#1350ce',
  'PM': '#6995ba',
  'ZM': '#f53b2a',
  'EE': '#e1cf3b',
  'EG': '#679c9d',
  'ZA': '#e08c56',
  'EC': '#ba96ce',
  'IT': '#c79ed2',
  'VN': '#1deaa7',
  'SB': '#947002',
  'ET': '#5be4f0',
  'SO': '#bde052',
  'ZW': '#b46238',
  'SA': '#96e591',
  'ES': '#28fcfd',
  'ER': '#48b41b',
  'MD': '#fc458e',
  'MG': '#e33e52',
  'MA': '#73872a',
  'MC': '#b2db15',
  'UZ': '#00efd4',
  'MM': '#cefcb8',
  'ML': '#6b2e5f',
  'MO': '#c79ed2',
  'MN': '#aa226d',
  'MH': '#1c271',
  'MK': '#d6dd92',
  'MU': '#9ab9b7',
  'MT': '#64820f',
  'MW': '#b2be57',
  'MV': '#1bb699',
  'MQ': '#9cb64a',
  'MP': '#e7dbce',
  'MS': '#792ed8',
  'MR': '#996c48',
  'IM': '#79352c',
  'UG': '#615af0',
  'MY': '#fa06ec',
  'MX': '#e3a481',
  'IL': '#521250',
  'FR': '#96b00c',
  'SH': '#c79bc2',
  'FI': '#be608b',
  'FJ': '#225b8',
  'FK': '#57c4d8',
  'FM': '#0eb621',
  'FO': '#a4d17a',
  'NI': '#1dc18',
  'NL': '#f1ae16',
  'NO': '#421f79',
  'NA': '#a5b3d9',
  'VU': '#7ad236',
  'NC': '#ef6e3c',
  'NE': '#dd93fd',
  'NG': '#3f8473',
  'NZ': '#243eeb',
  'NP': '#c4fd57',
  'NR': '#7d1d85',
  'CK': '#9e6d71',
  'CI': '#0cd36d',
  'CH': '#a84a8f',
  'CO': '#935b6d',
  'CN': '#2f1179',
  'CM': '#7e50a8',
  'CL': '#ffdbe1',
  'CA': '#c4d647',
  'CG': '#513d98',
  'CF': '#289812',
  'CD': '#aead3a',
  'CZ': '#ac3e1b',
  'CY': '#228916',
  'CR': '#4b5bdc',
  'CV': '#e0eeb8',
  'CU': '#cb5bea',
  'SZ': '#1ae6db',
  'SY': '#911e7e',
  'KG': '#d36647',
  'KE': '#6b2e5f',
  'SR': '#d02e29',
  'KI': '#64820f',
  'KH': '#ca4751',
  'SV': '#c6c42c',
  'KM': '#916988',
  'ST': '#060e27',
  'SK': '#4f0f6f',
  'KR': '#21538e',
  'SI': '#1d1d58',
  'KP': '#1c271',
  'KW': '#89d534',
  'SN': '#21d52e',
  'SM': '#8fd883',
  'SL': '#b47162',
  'SC': '#d00043',
  'KZ': '#1bb699',
  'KY': '#11dec1',
  'SG': '#1ec227',
  'SE': '#3e464c',
  'SD': '#36486a',
  'DO': '#f697c1',
  'DM': '#880977',
  'DJ': '#539397',
  'DK': '#df514a',
  'VG': '#06f43a',
  'DE': '#5426e0',
  'YE': '#dc1c06',
  'DZ': '#ea9e70',
  'US': '#79bca0',
  'UY': '#a8b8d4',
  'YT': '#06e052',
  'LB': '#3b8c2a',
  'LC': '#77772a',
  'LA': '#7fb411',
  'TV': '#406df9',
  'TW': '#3f16d9',
  'TT': '#fb4c03',
  'TR': '#62c03e',
  'LK': '#bb09b',
  'LI': '#ea24a3',
  'LV': '#0023b8',
  'TO': '#3d6751',
  'LT': '#79352c',
  'LU': '#521250',
  'LR': '#f50422',
  'LS': '#986b53',
  'TH': '#b4c086',
  'TG': '#30cc49',
  'TD': '#566ca0',
  'TC': '#88aa0b',
  'LY': '#983f7a',
  'VA': '#21538e',
  'VC': '#fc6b57',
  'AE': '#2a3434',
  'AD': '#c6e1e8',
  'AG': '#f205e6',
  'AF': '#63b598',
  'AI': '#0d5ac1',
  'VI': '#823c59',
  'IS': '#0023b8',
  'IR': '#f50422',
  'AM': '#14a9ad',
  'AL': '#ce7d78',
  'AO': '#648177',
  'AN': '#8fe22a',
  'AS': '#a48a9e',
  'AR': '#1c0365',
  'AU': '#a4e43f',
  'AT': '#d298e2',
  'AW': '#4ca2f9',
  'IN': '#3b8c2a',
  'TZ': '#ac7c0a',
  'AZ': '#6119d0',
  'IE': '#ea24a3',
  'ID': '#986b53',
  'UA': '#4be47',
  'QA': '#cb2582',
  'MZ': '#520d3a'}